---
- name: command module demo
  hosts: all
  tasks:
    - name: show list of files
      #ansible.builtin.command: 'ls -l *' --> command module does not support *
      ansible.builtin.shell: 'ls -l *'
      register: command_output
    - name: command output
      ansible.builtin.debug:
      var: command_output.stdout_lines