---
- name: copy module demo
  hosts: all
  become: false
  tasks:
    - name: copy report.txt
      ansible.builtin.copy:
        src: report.txt # in text file was "this is test"
        dest: /home/devops/report.txt
        owner: devops #
        mode: '0644' #