---
- name: group module demo
  hosts: all
  become: true
  vars:
    myuser: "ubuntu_5"
    mygroup: "ubuntu_2" #should exists
  tasks:
    - name: change primary group
      ansible.builtin.user: # user module not group
        name: "{{ myuser}}"
        groups: "{{ mygroup }}"

# id <user> --> shows the group
# groups <user>
