---

- name: user module demo
  hosts: all
  become: true
  tasks:
    # make one group of wheel
    # - name: Ensure wheel group exists
    #   ansible.builtin.group:
    #     name: wheel
    #     state: present
    - name: Ensure wheel and adm groups exist
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - wheel
        - adm

    - name: user example present
      ansible.builtin.user:
        name: example
        password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
        groups:
          - wheel
          - adm
        state: present
        shell: "/bin/bash"
        system: false
        create_home: true
        home: "/home/example"
        comment: "Ansible example"
        generate_ssh_key: true
