---
- name: copy module demo
  hosts: all
  vars:
    myfile: "~/wordpress/write_inside_file.txt"
  tasks:
    - name: create a simple text file
      ansible.builtin.copy:
        dest: "{{ myfile }}"
        content: |
          line 1
          line 2
          etc.
