---
- name: file module demo
  hosts: all
  vars:
    mylink: "~/link"
    myfile: "~/example"
  tasks:
    - name: Creating hardlink
      ansible.builtin.file:
        src: "{{ myfile }}"
        dest: "{{ mylink }}"
        state: hard