---
- name: file module demo
  hosts: all
  vars:
    mydir: "~/wordpress/example"
  tasks:
    - name: Creating a directory
      ansible.builtin.file:
        path: "{{ mydir }}"
        state: directory
        owner: root
        group: docker
        mode: '0644'